# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Instalar NestJS CLI globalmente para desarrollo
RUN npm install -g @nestjs/cli

# Instalar definiciones de tipo para Node.js (si son necesarias)
RUN npm install @types/node --save-dev

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:dev"]
