# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Instalar NestJS CLI globalmente
RUN npm install -g @nestjs/cli

# Copy the rest of the application
COPY . .

COPY .prod_env /app/.prod_env

ENV NODE_ENV=production

RUN npm install --save-dev @types/node

RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "dist/main"]
